CREATE DATABASE PRODUCTS_APP;
GRANT ALL PRIVILEGES ON PRODUCTS_APP.* TO 'test'@'localhost';



CREATE TABLE PRODUCT(
    ID INT AUTO_INCREMENT,
    SKU VARCHAR(100),
    NAME VARCHAR (100) NOT NULL,
    DESCRIPTION TEXT,
    QUANTITY INT DEFAULT 0,
    PRICE DECIMAL(50,2) DEFAULT 0.00,    
    PRIMARY KEY(ID)
);

CREATE TABLE CATEGORY(
    CODE VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY(CODE)
);

CREATE TABLE PRODUCT_CATEGORY(
    ID INT AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL,
    CATEGORY_CODE VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY(CATEGORY_CODE) REFERENCES `CATEGORY`(CODE)
);

